# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    guzzle.api_new_ws:
        alias: guzzle.client.api_new_ws

    app.neo_ws:
        class: AppBundle\Service\NeoWsService
        arguments: [ "@guzzle.api_new_ws", "%neo_ws%" ]
